### ISSUE TITLE
Erro no parcel

### ISSUE THREAD

**Issue by naylsonrj** [desenvolvweb/basic-front-boilerplate#23]
Como resolver esse problema no start
foi feita a instalação normalmente, preciso instalar o parcel separadamente ?  

![image](https://user-images.githubusercontent.com/83142707/173199246-02fdd740-4843-4b2f-8a6e-b75bb8be331d.png)

@parcel/transformer-css: Could not resolve module
"C:\Users\naylson\Desktop\naylson-git\Javascript\PotterJS\node_modules\@parcel\css\parcel-css.win32-x64.node" from
"C:\Users\naylson\Desktop\naylson-git\Javascript\PotterJS\node_modules\@parcel\css\node\index.js"

  Error: Could not resolve module "C:\Users\naylson\Desktop\naylson-git\Javascript\PotterJS\node_modules\@parcel\css\parcel-css.win32-x64.node"    
  from "C:\Users\naylson\Desktop\naylson-git\Javascript\PotterJS\node_modules\@parcel\css\node\index.js"
  at $0578d0f6e116167e$export$fb2a0b866a8162dc.resolve
  (C:\Users\naylson\Desktop\naylson-git\Javascript\PotterJS\node_modules\@parcel\package-manager\lib\index.js:4919:21)
  at NodePackageManager.resolveSync
  (C:\Users\naylson\Desktop\naylson-git\Javascript\PotterJS\node_modules\@parcel\package-manager\lib\index.js:3510:42)
  at NodePackageManager.requireSync
  (C:\Users\naylson\Desktop\naylson-git\Javascript\PotterJS\node_modules\@parcel\package-manager\lib\index.js:3351:34)
  at Module.m.require (C:\Users\naylson\Desktop\naylson-git\Javascript\PotterJS\node_modules\@parcel\package-manager\lib\index.js:3365:25)
  at require (node:internal/modules/cjs/helpers:102:18)
  at Object.<anonymous> (C:\Users\naylson\Desktop\naylson-git\Javascript\PotterJS\node_modules\@parcel\css\node\index.js:21:22)
  at Module._compile (node:internal/modules/cjs/loader:1103:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
  at Module.load (node:internal/modules/cjs/loader:981:32)
  at NodePackageManager.load (C:\Users\naylson\Desktop\naylson-git\Javascript\PotterJS\node_modules\@parcel\package-manager\lib\index.js:3374:15)

**Comment by brunotortelli** [comment]
Eu tive o mesmo problema, e a solução que eu encontrei foi essa.

`npm install --save-dev @parcel/css`

**Comment by saulopaiva** [comment]
Fala, pessoal!

@naylsonrj não precisa instalar o parcel separadamente não.

Podem confirmar a versão do NPM que estão usando? É a mesma do arquivo `.nvmrc` na raiz do projeto?

**Comment by naylsonrj** [comment]
> a

estou com ultima versão 
npm 8.12.1
node v16.14.2

**Comment by brunotortelli** [comment]
npm 8.10.0
node v16.15.0

**Comment by saulopaiva** [comment]
Opa, joia.

Por aqui estamos na versão `v16.14.2`. A diferença pode estar no SO, estou no Linux.

A dependencia indicada pelo @brunotortelli pode ser inserida oficialmente.

@naylsonrj pode confirmar se ao instalar `npm install --save-dev @parcel/css`, o projeto funciona normalmente?

**Comment by naylsonrj** [comment]
rodando depois desse comando: `npm install --save-dev @parcel/css`
obrigado 

![image](https://user-images.githubusercontent.com/83142707/174152606-223d3a86-9cb0-4426-9193-1ec93f2ae5a5.png)

**Comment by saulopaiva** [comment]
Já que deu certo, vamos colocar oficialmete no repo. Obrigado pela contribuição pessoal!
